#include "iso639/cIso639.h"

/*******************************************************************************
********************************************************* Types and Definitions
********************************************************************************
 https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt
*******************************************************************************/

#define c_c_( Str ) (cChars){ .s=strlen(Str), .v=Str }
#define a2_( A, B ) (cIso639){ .code={ A, B, '\0', '\0' } }
#define a3_( A, B, C ) (cIso639){ .code={ A, B, C, '\0' } }

static cIso639Info raw[487] = {
	(cIso639Info){ a2_( 'a', 'a' ), a3_( 'a', 'a', 'r' ), a3_( 'a', 'a', 'r' ), c_c_( "Afar" ) },
   (cIso639Info){ a2_( 'a', 'b' ), a3_( 'a', 'b', 'k' ), a3_( 'a', 'b', 'k' ), c_c_( "Abkhazian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'c', 'e' ), a3_( 'a', 'c', 'e' ), c_c_( "Achinese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'c', 'h' ), a3_( 'a', 'c', 'h' ), c_c_( "Acoli" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'd', 'a' ), a3_( 'a', 'd', 'a' ), c_c_( "Adangme" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'd', 'y' ), a3_( 'a', 'd', 'y' ), c_c_( "Adyghe; Adygei" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'f', 'a' ), a3_( 'a', 'f', 'a' ), c_c_( "Afro-Asiatic languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'f', 'h' ), a3_( 'a', 'f', 'h' ), c_c_( "Afrihili" ) },
   (cIso639Info){ a2_( 'a', 'f' ), a3_( 'a', 'f', 'r' ), a3_( 'a', 'f', 'r' ), c_c_( "Afrikaans" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'i', 'n' ), a3_( 'a', 'i', 'n' ), c_c_( "Ainu" ) },
   (cIso639Info){ a2_( 'a', 'k' ), a3_( 'a', 'k', 'a' ), a3_( 'a', 'k', 'a' ), c_c_( "Akan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'k', 'k' ), a3_( 'a', 'k', 'k' ), c_c_( "Akkadian" ) },
   (cIso639Info){ a2_( 's', 'q' ), a3_( 'a', 'l', 'b' ), a3_( 's', 'q', 'i' ), c_c_( "Albanian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'l', 'e' ), a3_( 'a', 'l', 'e' ), c_c_( "Aleut" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'l', 'g' ), a3_( 'a', 'l', 'g' ), c_c_( "Algonquian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'l', 't' ), a3_( 'a', 'l', 't' ), c_c_( "Southern Altai" ) },
   (cIso639Info){ a2_( 'a', 'm' ), a3_( 'a', 'm', 'h' ), a3_( 'a', 'm', 'h' ), c_c_( "Amharic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'n', 'g' ), a3_( 'a', 'n', 'g' ), c_c_( "English, Old (ca.450-1100)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'n', 'p' ), a3_( 'a', 'n', 'p' ), c_c_( "Angika" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'p', 'a' ), a3_( 'a', 'p', 'a' ), c_c_( "Apache languages" ) },
   (cIso639Info){ a2_( 'a', 'r' ), a3_( 'a', 'r', 'a' ), a3_( 'a', 'r', 'a' ), c_c_( "Arabic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'r', 'c' ), a3_( 'a', 'r', 'c' ), c_c_( "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)" ) },
   (cIso639Info){ a2_( 'a', 'n' ), a3_( 'a', 'r', 'g' ), a3_( 'a', 'r', 'g' ), c_c_( "Aragonese" ) },
   (cIso639Info){ a2_( 'h', 'y' ), a3_( 'a', 'r', 'm' ), a3_( 'h', 'y', 'e' ), c_c_( "Armenian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'r', 'n' ), a3_( 'a', 'r', 'n' ), c_c_( "Mapudungun; Mapuche" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'r', 'p' ), a3_( 'a', 'r', 'p' ), c_c_( "Arapaho" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'r', 't' ), a3_( 'a', 'r', 't' ), c_c_( "Artificial languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'r', 'w' ), a3_( 'a', 'r', 'w' ), c_c_( "Arawak" ) },
   (cIso639Info){ a2_( 'a', 's' ), a3_( 'a', 's', 'm' ), a3_( 'a', 's', 'm' ), c_c_( "Assamese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 's', 't' ), a3_( 'a', 's', 't' ), c_c_( "Asturian; Bable; Leonese; Asturleonese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 't', 'h' ), a3_( 'a', 't', 'h' ), c_c_( "Athapascan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'u', 's' ), a3_( 'a', 'u', 's' ), c_c_( "Australian languages" ) },
   (cIso639Info){ a2_( 'a', 'v' ), a3_( 'a', 'v', 'a' ), a3_( 'a', 'v', 'a' ), c_c_( "Avaric" ) },
   (cIso639Info){ a2_( 'a', 'e' ), a3_( 'a', 'v', 'e' ), a3_( 'a', 'v', 'e' ), c_c_( "Avestan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'a', 'w', 'a' ), a3_( 'a', 'w', 'a' ), c_c_( "Awadhi" ) },
   (cIso639Info){ a2_( 'a', 'y' ), a3_( 'a', 'y', 'm' ), a3_( 'a', 'y', 'm' ), c_c_( "Aymara" ) },
   (cIso639Info){ a2_( 'a', 'z' ), a3_( 'a', 'z', 'e' ), a3_( 'a', 'z', 'e' ), c_c_( "Azerbaijani" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'a', 'd' ), a3_( 'b', 'a', 'd' ), c_c_( "Banda languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'a', 'i' ), a3_( 'b', 'a', 'i' ), c_c_( "Bamileke languages" ) },
   (cIso639Info){ a2_( 'b', 'a' ), a3_( 'b', 'a', 'k' ), a3_( 'b', 'a', 'k' ), c_c_( "Bashkir" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'a', 'l' ), a3_( 'b', 'a', 'l' ), c_c_( "Baluchi" ) },
   (cIso639Info){ a2_( 'b', 'm' ), a3_( 'b', 'a', 'm' ), a3_( 'b', 'a', 'm' ), c_c_( "Bambara" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'a', 'n' ), a3_( 'b', 'a', 'n' ), c_c_( "Balinese" ) },
   (cIso639Info){ a2_( 'e', 'u' ), a3_( 'b', 'a', 'q' ), a3_( 'e', 'u', 's' ), c_c_( "Basque" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'a', 's' ), a3_( 'b', 'a', 's' ), c_c_( "Basa" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'a', 't' ), a3_( 'b', 'a', 't' ), c_c_( "Baltic languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'e', 'j' ), a3_( 'b', 'e', 'j' ), c_c_( "Beja; Bedawiyet" ) },
   (cIso639Info){ a2_( 'b', 'e' ), a3_( 'b', 'e', 'l' ), a3_( 'b', 'e', 'l' ), c_c_( "Belarusian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'e', 'm' ), a3_( 'b', 'e', 'm' ), c_c_( "Bemba" ) },
   (cIso639Info){ a2_( 'b', 'n' ), a3_( 'b', 'e', 'n' ), a3_( 'b', 'e', 'n' ), c_c_( "Bengali" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'e', 'r' ), a3_( 'b', 'e', 'r' ), c_c_( "Berber languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'h', 'o' ), a3_( 'b', 'h', 'o' ), c_c_( "Bhojpuri" ) },
   (cIso639Info){ a2_( 'b', 'h' ), a3_( 'b', 'i', 'h' ), a3_( 'b', 'i', 'h' ), c_c_( "Bihari languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'i', 'k' ), a3_( 'b', 'i', 'k' ), c_c_( "Bikol" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'i', 'n' ), a3_( 'b', 'i', 'n' ), c_c_( "Bini; Edo" ) },
   (cIso639Info){ a2_( 'b', 'i' ), a3_( 'b', 'i', 's' ), a3_( 'b', 'i', 's' ), c_c_( "Bislama" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'l', 'a' ), a3_( 'b', 'l', 'a' ), c_c_( "Siksika" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'n', 't' ), a3_( 'b', 'n', 't' ), c_c_( "Bantu languages" ) },
   (cIso639Info){ a2_( 'b', 's' ), a3_( 'b', 'o', 's' ), a3_( 'b', 'o', 's' ), c_c_( "Bosnian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'r', 'a' ), a3_( 'b', 'r', 'a' ), c_c_( "Braj" ) },
   (cIso639Info){ a2_( 'b', 'r' ), a3_( 'b', 'r', 'e' ), a3_( 'b', 'r', 'e' ), c_c_( "Breton" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 't', 'k' ), a3_( 'b', 't', 'k' ), c_c_( "Batak languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'u', 'a' ), a3_( 'b', 'u', 'a' ), c_c_( "Buriat" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'u', 'g' ), a3_( 'b', 'u', 'g' ), c_c_( "Buginese" ) },
   (cIso639Info){ a2_( 'b', 'g' ), a3_( 'b', 'u', 'l' ), a3_( 'b', 'u', 'l' ), c_c_( "Bulgarian" ) },
   (cIso639Info){ a2_( 'm', 'y' ), a3_( 'b', 'u', 'r' ), a3_( 'm', 'y', 'a' ), c_c_( "Burmese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'b', 'y', 'n' ), a3_( 'b', 'y', 'n' ), c_c_( "Blin; Bilin" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'a', 'd' ), a3_( 'c', 'a', 'd' ), c_c_( "Caddo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'a', 'i' ), a3_( 'c', 'a', 'i' ), c_c_( "Central American Indian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'a', 'r' ), a3_( 'c', 'a', 'r' ), c_c_( "Galibi Carib" ) },
   (cIso639Info){ a2_( 'c', 'a' ), a3_( 'c', 'a', 't' ), a3_( 'c', 'a', 't' ), c_c_( "Catalan; Valencian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'a', 'u' ), a3_( 'c', 'a', 'u' ), c_c_( "Caucasian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'e', 'b' ), a3_( 'c', 'e', 'b' ), c_c_( "Cebuano" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'e', 'l' ), a3_( 'c', 'e', 'l' ), c_c_( "Celtic languages" ) },
   (cIso639Info){ a2_( 'c', 'h' ), a3_( 'c', 'h', 'a' ), a3_( 'c', 'h', 'a' ), c_c_( "Chamorro" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'b' ), a3_( 'c', 'h', 'b' ), c_c_( "Chibcha" ) },
   (cIso639Info){ a2_( 'c', 'e' ), a3_( 'c', 'h', 'e' ), a3_( 'c', 'h', 'e' ), c_c_( "Chechen" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'g' ), a3_( 'c', 'h', 'g' ), c_c_( "Chagatai" ) },
   (cIso639Info){ a2_( 'z', 'h' ), a3_( 'c', 'h', 'i' ), a3_( 'z', 'h', 'o' ), c_c_( "Chinese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'k' ), a3_( 'c', 'h', 'k' ), c_c_( "Chuukese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'm' ), a3_( 'c', 'h', 'm' ), c_c_( "Mari" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'n' ), a3_( 'c', 'h', 'n' ), c_c_( "Chinook jargon" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'o' ), a3_( 'c', 'h', 'o' ), c_c_( "Choctaw" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'p' ), a3_( 'c', 'h', 'p' ), c_c_( "Chipewyan; Dene Suline" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'r' ), a3_( 'c', 'h', 'r' ), c_c_( "Cherokee" ) },
   (cIso639Info){ a2_( 'c', 'u' ), a3_( 'c', 'h', 'u' ), a3_( 'c', 'h', 'u' ), c_c_( "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" ) },
   (cIso639Info){ a2_( 'c', 'v' ), a3_( 'c', 'h', 'v' ), a3_( 'c', 'h', 'v' ), c_c_( "Chuvash" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'h', 'y' ), a3_( 'c', 'h', 'y' ), c_c_( "Cheyenne" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'm', 'c' ), a3_( 'c', 'm', 'c' ), c_c_( "Chamic languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'n', 'r' ), a3_( 'c', 'n', 'r' ), c_c_( "Montenegrin" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'o', 'p' ), a3_( 'c', 'o', 'p' ), c_c_( "Coptic" ) },
   (cIso639Info){ a2_( 'k', 'w' ), a3_( 'c', 'o', 'r' ), a3_( 'c', 'o', 'r' ), c_c_( "Cornish" ) },
   (cIso639Info){ a2_( 'c', 'o' ), a3_( 'c', 'o', 's' ), a3_( 'c', 'o', 's' ), c_c_( "Corsican" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'p', 'e' ), a3_( 'c', 'p', 'e' ), c_c_( "Creoles and pidgins, English based" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'p', 'f' ), a3_( 'c', 'p', 'f' ), c_c_( "Creoles and pidgins, French-based" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'p', 'p' ), a3_( 'c', 'p', 'p' ), c_c_( "Creoles and pidgins, Portuguese-based" ) },
   (cIso639Info){ a2_( 'c', 'r' ), a3_( 'c', 'r', 'e' ), a3_( 'c', 'r', 'e' ), c_c_( "Cree" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'r', 'h' ), a3_( 'c', 'r', 'h' ), c_c_( "Crimean Tatar; Crimean Turkish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'r', 'p' ), a3_( 'c', 'r', 'p' ), c_c_( "Creoles and pidgins" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 's', 'b' ), a3_( 'c', 's', 'b' ), c_c_( "Kashubian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'c', 'u', 's' ), a3_( 'c', 'u', 's' ), c_c_( "Cushitic languages" ) },
   (cIso639Info){ a2_( 'c', 's' ), a3_( 'c', 'z', 'e' ), a3_( 'c', 'e', 's' ), c_c_( "Czech" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'a', 'k' ), a3_( 'd', 'a', 'k' ), c_c_( "Dakota" ) },
   (cIso639Info){ a2_( 'd', 'a' ), a3_( 'd', 'a', 'n' ), a3_( 'd', 'a', 'n' ), c_c_( "Danish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'a', 'r' ), a3_( 'd', 'a', 'r' ), c_c_( "Dargwa" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'a', 'y' ), a3_( 'd', 'a', 'y' ), c_c_( "Land Dayak languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'e', 'l' ), a3_( 'd', 'e', 'l' ), c_c_( "Delaware" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'e', 'n' ), a3_( 'd', 'e', 'n' ), c_c_( "Slave (Athapascan)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'g', 'r' ), a3_( 'd', 'g', 'r' ), c_c_( "Dogrib" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'i', 'n' ), a3_( 'd', 'i', 'n' ), c_c_( "Dinka" ) },
   (cIso639Info){ a2_( 'd', 'v' ), a3_( 'd', 'i', 'v' ), a3_( 'd', 'i', 'v' ), c_c_( "Divehi; Dhivehi; Maldivian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'o', 'i' ), a3_( 'd', 'o', 'i' ), c_c_( "Dogri" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'r', 'a' ), a3_( 'd', 'r', 'a' ), c_c_( "Dravidian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 's', 'b' ), a3_( 'd', 's', 'b' ), c_c_( "Lower Sorbian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'u', 'a' ), a3_( 'd', 'u', 'a' ), c_c_( "Duala" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'u', 'm' ), a3_( 'd', 'u', 'm' ), c_c_( "Dutch, Middle (ca.1050-1350)" ) },
   (cIso639Info){ a2_( 'n', 'l' ), a3_( 'd', 'u', 't' ), a3_( 'n', 'l', 'd' ), c_c_( "Dutch; Flemish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'd', 'y', 'u' ), a3_( 'd', 'y', 'u' ), c_c_( "Dyula" ) },
   (cIso639Info){ a2_( 'd', 'z' ), a3_( 'd', 'z', 'o' ), a3_( 'd', 'z', 'o' ), c_c_( "Dzongkha" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'e', 'f', 'i' ), a3_( 'e', 'f', 'i' ), c_c_( "Efik" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'e', 'g', 'y' ), a3_( 'e', 'g', 'y' ), c_c_( "Egyptian (Ancient)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'e', 'k', 'a' ), a3_( 'e', 'k', 'a' ), c_c_( "Ekajuk" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'e', 'l', 'x' ), a3_( 'e', 'l', 'x' ), c_c_( "Elamite" ) },
   (cIso639Info){ a2_( 'e', 'n' ), a3_( 'e', 'n', 'g' ), a3_( 'e', 'n', 'g' ), c_c_( "English" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'e', 'n', 'm' ), a3_( 'e', 'n', 'm' ), c_c_( "English, Middle (1100-1500)" ) },
   (cIso639Info){ a2_( 'e', 'o' ), a3_( 'e', 'p', 'o' ), a3_( 'e', 'p', 'o' ), c_c_( "Esperanto" ) },
   (cIso639Info){ a2_( 'e', 't' ), a3_( 'e', 's', 't' ), a3_( 'e', 's', 't' ), c_c_( "Estonian" ) },
   (cIso639Info){ a2_( 'e', 'e' ), a3_( 'e', 'w', 'e' ), a3_( 'e', 'w', 'e' ), c_c_( "Ewe" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'e', 'w', 'o' ), a3_( 'e', 'w', 'o' ), c_c_( "Ewondo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'a', 'n' ), a3_( 'f', 'a', 'n' ), c_c_( "Fang" ) },
   (cIso639Info){ a2_( 'f', 'o' ), a3_( 'f', 'a', 'o' ), a3_( 'f', 'a', 'o' ), c_c_( "Faroese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'a', 't' ), a3_( 'f', 'a', 't' ), c_c_( "Fanti" ) },
   (cIso639Info){ a2_( 'f', 'j' ), a3_( 'f', 'i', 'j' ), a3_( 'f', 'i', 'j' ), c_c_( "Fijian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'i', 'l' ), a3_( 'f', 'i', 'l' ), c_c_( "Filipino; Pilipino" ) },
   (cIso639Info){ a2_( 'f', 'i' ), a3_( 'f', 'i', 'n' ), a3_( 'f', 'i', 'n' ), c_c_( "Finnish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'i', 'u' ), a3_( 'f', 'i', 'u' ), c_c_( "Finno-Ugrian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'o', 'n' ), a3_( 'f', 'o', 'n' ), c_c_( "Fon" ) },
   (cIso639Info){ a2_( 'f', 'r' ), a3_( 'f', 'r', 'e' ), a3_( 'f', 'r', 'a' ), c_c_( "French" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'r', 'm' ), a3_( 'f', 'r', 'm' ), c_c_( "French, Middle (ca.1400-1600)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'r', 'o' ), a3_( 'f', 'r', 'o' ), c_c_( "French, Old (842-ca.1400)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'r', 'r' ), a3_( 'f', 'r', 'r' ), c_c_( "Northern Frisian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'r', 's' ), a3_( 'f', 'r', 's' ), c_c_( "Eastern Frisian" ) },
   (cIso639Info){ a2_( 'f', 'y' ), a3_( 'f', 'r', 'y' ), a3_( 'f', 'r', 'y' ), c_c_( "Western Frisian" ) },
   (cIso639Info){ a2_( 'f', 'f' ), a3_( 'f', 'u', 'l' ), a3_( 'f', 'u', 'l' ), c_c_( "Fulah" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'f', 'u', 'r' ), a3_( 'f', 'u', 'r' ), c_c_( "Friulian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'a', 'a' ), a3_( 'g', 'a', 'a' ), c_c_( "Ga" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'a', 'y' ), a3_( 'g', 'a', 'y' ), c_c_( "Gayo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'b', 'a' ), a3_( 'g', 'b', 'a' ), c_c_( "Gbaya" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'e', 'm' ), a3_( 'g', 'e', 'm' ), c_c_( "Germanic languages" ) },
   (cIso639Info){ a2_( 'k', 'a' ), a3_( 'g', 'e', 'o' ), a3_( 'k', 'a', 't' ), c_c_( "Georgian" ) },
   (cIso639Info){ a2_( 'd', 'e' ), a3_( 'g', 'e', 'r' ), a3_( 'd', 'e', 'u' ), c_c_( "German" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'e', 'z' ), a3_( 'g', 'e', 'z' ), c_c_( "Geez" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'i', 'l' ), a3_( 'g', 'i', 'l' ), c_c_( "Gilbertese" ) },
   (cIso639Info){ a2_( 'g', 'd' ), a3_( 'g', 'l', 'a' ), a3_( 'g', 'l', 'a' ), c_c_( "Gaelic; Scottish Gaelic" ) },
   (cIso639Info){ a2_( 'g', 'a' ), a3_( 'g', 'l', 'e' ), a3_( 'g', 'l', 'e' ), c_c_( "Irish" ) },
   (cIso639Info){ a2_( 'g', 'l' ), a3_( 'g', 'l', 'g' ), a3_( 'g', 'l', 'g' ), c_c_( "Galician" ) },
   (cIso639Info){ a2_( 'g', 'v' ), a3_( 'g', 'l', 'v' ), a3_( 'g', 'l', 'v' ), c_c_( "Manx" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'm', 'h' ), a3_( 'g', 'm', 'h' ), c_c_( "German, Middle High (ca.1050-1500)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'o', 'h' ), a3_( 'g', 'o', 'h' ), c_c_( "German, Old High (ca.750-1050)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'o', 'n' ), a3_( 'g', 'o', 'n' ), c_c_( "Gondi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'o', 'r' ), a3_( 'g', 'o', 'r' ), c_c_( "Gorontalo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'o', 't' ), a3_( 'g', 'o', 't' ), c_c_( "Gothic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'r', 'b' ), a3_( 'g', 'r', 'b' ), c_c_( "Grebo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'r', 'c' ), a3_( 'g', 'r', 'c' ), c_c_( "Greek, Ancient (to 1453)" ) },
   (cIso639Info){ a2_( 'e', 'l' ), a3_( 'g', 'r', 'e' ), a3_( 'e', 'l', 'l' ), c_c_( "Greek, Modern (1453-)" ) },
   (cIso639Info){ a2_( 'g', 'n' ), a3_( 'g', 'r', 'n' ), a3_( 'g', 'r', 'n' ), c_c_( "Guarani" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 's', 'w' ), a3_( 'g', 's', 'w' ), c_c_( "Swiss German; Alemannic; Alsatian" ) },
   (cIso639Info){ a2_( 'g', 'u' ), a3_( 'g', 'u', 'j' ), a3_( 'g', 'u', 'j' ), c_c_( "Gujarati" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'g', 'w', 'i' ), a3_( 'g', 'w', 'i' ), c_c_( "Gwich'in" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'a', 'i' ), a3_( 'h', 'a', 'i' ), c_c_( "Haida" ) },
   (cIso639Info){ a2_( 'h', 't' ), a3_( 'h', 'a', 't' ), a3_( 'h', 'a', 't' ), c_c_( "Haitian; Haitian Creole" ) },
   (cIso639Info){ a2_( 'h', 'a' ), a3_( 'h', 'a', 'u' ), a3_( 'h', 'a', 'u' ), c_c_( "Hausa" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'a', 'w' ), a3_( 'h', 'a', 'w' ), c_c_( "Hawaiian" ) },
   (cIso639Info){ a2_( 'h', 'e' ), a3_( 'h', 'e', 'b' ), a3_( 'h', 'e', 'b' ), c_c_( "Hebrew" ) },
   (cIso639Info){ a2_( 'h', 'z' ), a3_( 'h', 'e', 'r' ), a3_( 'h', 'e', 'r' ), c_c_( "Herero" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'i', 'l' ), a3_( 'h', 'i', 'l' ), c_c_( "Hiligaynon" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'i', 'm' ), a3_( 'h', 'i', 'm' ), c_c_( "Himachali languages; Western Pahari languages" ) },
   (cIso639Info){ a2_( 'h', 'i' ), a3_( 'h', 'i', 'n' ), a3_( 'h', 'i', 'n' ), c_c_( "Hindi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'i', 't' ), a3_( 'h', 'i', 't' ), c_c_( "Hittite" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'm', 'n' ), a3_( 'h', 'm', 'n' ), c_c_( "Hmong; Mong" ) },
   (cIso639Info){ a2_( 'h', 'o' ), a3_( 'h', 'm', 'o' ), a3_( 'h', 'm', 'o' ), c_c_( "Hiri Motu" ) },
   (cIso639Info){ a2_( 'h', 'r' ), a3_( 'h', 'r', 'v' ), a3_( 'h', 'r', 'v' ), c_c_( "Croatian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 's', 'b' ), a3_( 'h', 's', 'b' ), c_c_( "Upper Sorbian" ) },
   (cIso639Info){ a2_( 'h', 'u' ), a3_( 'h', 'u', 'n' ), a3_( 'h', 'u', 'n' ), c_c_( "Hungarian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'h', 'u', 'p' ), a3_( 'h', 'u', 'p' ), c_c_( "Hupa" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'b', 'a' ), a3_( 'i', 'b', 'a' ), c_c_( "Iban" ) },
   (cIso639Info){ a2_( 'i', 'g' ), a3_( 'i', 'b', 'o' ), a3_( 'i', 'b', 'o' ), c_c_( "Igbo" ) },
   (cIso639Info){ a2_( 'i', 's' ), a3_( 'i', 'c', 'e' ), a3_( 'i', 's', 'l' ), c_c_( "Icelandic" ) },
   (cIso639Info){ a2_( 'i', 'o' ), a3_( 'i', 'd', 'o' ), a3_( 'i', 'd', 'o' ), c_c_( "Ido" ) },
   (cIso639Info){ a2_( 'i', 'i' ), a3_( 'i', 'i', 'i' ), a3_( 'i', 'i', 'i' ), c_c_( "Sichuan Yi; Nuosu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'j', 'o' ), a3_( 'i', 'j', 'o' ), c_c_( "Ijo languages" ) },
   (cIso639Info){ a2_( 'i', 'u' ), a3_( 'i', 'k', 'u' ), a3_( 'i', 'k', 'u' ), c_c_( "Inuktitut" ) },
   (cIso639Info){ a2_( 'i', 'e' ), a3_( 'i', 'l', 'e' ), a3_( 'i', 'l', 'e' ), c_c_( "Interlingue; Occidental" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'l', 'o' ), a3_( 'i', 'l', 'o' ), c_c_( "Iloko" ) },
   (cIso639Info){ a2_( 'i', 'a' ), a3_( 'i', 'n', 'a' ), a3_( 'i', 'n', 'a' ), c_c_( "Interlingua (International Auxiliary Language Association)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'n', 'c' ), a3_( 'i', 'n', 'c' ), c_c_( "Indic languages" ) },
   (cIso639Info){ a2_( 'i', 'd' ), a3_( 'i', 'n', 'd' ), a3_( 'i', 'n', 'd' ), c_c_( "Indonesian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'n', 'e' ), a3_( 'i', 'n', 'e' ), c_c_( "Indo-European languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'n', 'h' ), a3_( 'i', 'n', 'h' ), c_c_( "Ingush" ) },
   (cIso639Info){ a2_( 'i', 'k' ), a3_( 'i', 'p', 'k' ), a3_( 'i', 'p', 'k' ), c_c_( "Inupiaq" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'r', 'a' ), a3_( 'i', 'r', 'a' ), c_c_( "Iranian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'i', 'r', 'o' ), a3_( 'i', 'r', 'o' ), c_c_( "Iroquoian languages" ) },
   (cIso639Info){ a2_( 'i', 't' ), a3_( 'i', 't', 'a' ), a3_( 'i', 't', 'a' ), c_c_( "Italian" ) },
   (cIso639Info){ a2_( 'j', 'v' ), a3_( 'j', 'a', 'v' ), a3_( 'j', 'a', 'v' ), c_c_( "Javanese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'j', 'b', 'o' ), a3_( 'j', 'b', 'o' ), c_c_( "Lojban" ) },
   (cIso639Info){ a2_( 'j', 'a' ), a3_( 'j', 'p', 'n' ), a3_( 'j', 'p', 'n' ), c_c_( "Japanese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'j', 'p', 'r' ), a3_( 'j', 'p', 'r' ), c_c_( "Judeo-Persian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'j', 'r', 'b' ), a3_( 'j', 'r', 'b' ), c_c_( "Judeo-Arabic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'a', 'a' ), a3_( 'k', 'a', 'a' ), c_c_( "Kara-Kalpak" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'a', 'b' ), a3_( 'k', 'a', 'b' ), c_c_( "Kabyle" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'a', 'c' ), a3_( 'k', 'a', 'c' ), c_c_( "Kachin; Jingpho" ) },
   (cIso639Info){ a2_( 'k', 'l' ), a3_( 'k', 'a', 'l' ), a3_( 'k', 'a', 'l' ), c_c_( "Kalaallisut; Greenlandic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'a', 'm' ), a3_( 'k', 'a', 'm' ), c_c_( "Kamba" ) },
   (cIso639Info){ a2_( 'k', 'n' ), a3_( 'k', 'a', 'n' ), a3_( 'k', 'a', 'n' ), c_c_( "Kannada" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'a', 'r' ), a3_( 'k', 'a', 'r' ), c_c_( "Karen languages" ) },
   (cIso639Info){ a2_( 'k', 's' ), a3_( 'k', 'a', 's' ), a3_( 'k', 'a', 's' ), c_c_( "Kashmiri" ) },
   (cIso639Info){ a2_( 'k', 'r' ), a3_( 'k', 'a', 'u' ), a3_( 'k', 'a', 'u' ), c_c_( "Kanuri" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'a', 'w' ), a3_( 'k', 'a', 'w' ), c_c_( "Kawi" ) },
   (cIso639Info){ a2_( 'k', 'k' ), a3_( 'k', 'a', 'z' ), a3_( 'k', 'a', 'z' ), c_c_( "Kazakh" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'b', 'd' ), a3_( 'k', 'b', 'd' ), c_c_( "Kabardian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'h', 'a' ), a3_( 'k', 'h', 'a' ), c_c_( "Khasi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'h', 'i' ), a3_( 'k', 'h', 'i' ), c_c_( "Khoisan languages" ) },
   (cIso639Info){ a2_( 'k', 'm' ), a3_( 'k', 'h', 'm' ), a3_( 'k', 'h', 'm' ), c_c_( "Central Khmer" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'h', 'o' ), a3_( 'k', 'h', 'o' ), c_c_( "Khotanese; Sakan" ) },
   (cIso639Info){ a2_( 'k', 'i' ), a3_( 'k', 'i', 'k' ), a3_( 'k', 'i', 'k' ), c_c_( "Kikuyu; Gikuyu" ) },
   (cIso639Info){ a2_( 'r', 'w' ), a3_( 'k', 'i', 'n' ), a3_( 'k', 'i', 'n' ), c_c_( "Kinyarwanda" ) },
   (cIso639Info){ a2_( 'k', 'y' ), a3_( 'k', 'i', 'r' ), a3_( 'k', 'i', 'r' ), c_c_( "Kirghiz; Kyrgyz" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'm', 'b' ), a3_( 'k', 'm', 'b' ), c_c_( "Kimbundu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'o', 'k' ), a3_( 'k', 'o', 'k' ), c_c_( "Konkani" ) },
   (cIso639Info){ a2_( 'k', 'v' ), a3_( 'k', 'o', 'm' ), a3_( 'k', 'o', 'm' ), c_c_( "Komi" ) },
   (cIso639Info){ a2_( 'k', 'g' ), a3_( 'k', 'o', 'n' ), a3_( 'k', 'o', 'n' ), c_c_( "Kongo" ) },
   (cIso639Info){ a2_( 'k', 'o' ), a3_( 'k', 'o', 'r' ), a3_( 'k', 'o', 'r' ), c_c_( "Korean" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'o', 's' ), a3_( 'k', 'o', 's' ), c_c_( "Kosraean" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'p', 'e' ), a3_( 'k', 'p', 'e' ), c_c_( "Kpelle" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'r', 'c' ), a3_( 'k', 'r', 'c' ), c_c_( "Karachay-Balkar" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'r', 'l' ), a3_( 'k', 'r', 'l' ), c_c_( "Karelian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'r', 'o' ), a3_( 'k', 'r', 'o' ), c_c_( "Kru languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'r', 'u' ), a3_( 'k', 'r', 'u' ), c_c_( "Kurukh" ) },
   (cIso639Info){ a2_( 'k', 'j' ), a3_( 'k', 'u', 'a' ), a3_( 'k', 'u', 'a' ), c_c_( "Kuanyama; Kwanyama" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'u', 'm' ), a3_( 'k', 'u', 'm' ), c_c_( "Kumyk" ) },
   (cIso639Info){ a2_( 'k', 'u' ), a3_( 'k', 'u', 'r' ), a3_( 'k', 'u', 'r' ), c_c_( "Kurdish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'k', 'u', 't' ), a3_( 'k', 'u', 't' ), c_c_( "Kutenai" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'a', 'd' ), a3_( 'l', 'a', 'd' ), c_c_( "Ladino" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'a', 'h' ), a3_( 'l', 'a', 'h' ), c_c_( "Lahnda" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'a', 'm' ), a3_( 'l', 'a', 'm' ), c_c_( "Lamba" ) },
   (cIso639Info){ a2_( 'l', 'o' ), a3_( 'l', 'a', 'o' ), a3_( 'l', 'a', 'o' ), c_c_( "Lao" ) },
   (cIso639Info){ a2_( 'l', 'a' ), a3_( 'l', 'a', 't' ), a3_( 'l', 'a', 't' ), c_c_( "Latin" ) },
   (cIso639Info){ a2_( 'l', 'v' ), a3_( 'l', 'a', 'v' ), a3_( 'l', 'a', 'v' ), c_c_( "Latvian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'e', 'z' ), a3_( 'l', 'e', 'z' ), c_c_( "Lezghian" ) },
   (cIso639Info){ a2_( 'l', 'i' ), a3_( 'l', 'i', 'm' ), a3_( 'l', 'i', 'm' ), c_c_( "Limburgan; Limburger; Limburgish" ) },
   (cIso639Info){ a2_( 'l', 'n' ), a3_( 'l', 'i', 'n' ), a3_( 'l', 'i', 'n' ), c_c_( "Lingala" ) },
   (cIso639Info){ a2_( 'l', 't' ), a3_( 'l', 'i', 't' ), a3_( 'l', 'i', 't' ), c_c_( "Lithuanian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'o', 'l' ), a3_( 'l', 'o', 'l' ), c_c_( "Mongo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'o', 'z' ), a3_( 'l', 'o', 'z' ), c_c_( "Lozi" ) },
   (cIso639Info){ a2_( 'l', 'b' ), a3_( 'l', 't', 'z' ), a3_( 'l', 't', 'z' ), c_c_( "Luxembourgish; Letzeburgesch" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'u', 'a' ), a3_( 'l', 'u', 'a' ), c_c_( "Luba-Lulua" ) },
   (cIso639Info){ a2_( 'l', 'u' ), a3_( 'l', 'u', 'b' ), a3_( 'l', 'u', 'b' ), c_c_( "Luba-Katanga" ) },
   (cIso639Info){ a2_( 'l', 'g' ), a3_( 'l', 'u', 'g' ), a3_( 'l', 'u', 'g' ), c_c_( "Ganda" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'u', 'i' ), a3_( 'l', 'u', 'i' ), c_c_( "Luiseno" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'u', 'n' ), a3_( 'l', 'u', 'n' ), c_c_( "Lunda" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'u', 'o' ), a3_( 'l', 'u', 'o' ), c_c_( "Luo (Kenya and Tanzania)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'l', 'u', 's' ), a3_( 'l', 'u', 's' ), c_c_( "Lushai" ) },
   (cIso639Info){ a2_( 'm', 'k' ), a3_( 'm', 'a', 'c' ), a3_( 'm', 'k', 'd' ), c_c_( "Macedonian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 'd' ), a3_( 'm', 'a', 'd' ), c_c_( "Madurese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 'g' ), a3_( 'm', 'a', 'g' ), c_c_( "Magahi" ) },
   (cIso639Info){ a2_( 'm', 'h' ), a3_( 'm', 'a', 'h' ), a3_( 'm', 'a', 'h' ), c_c_( "Marshallese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 'i' ), a3_( 'm', 'a', 'i' ), c_c_( "Maithili" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 'k' ), a3_( 'm', 'a', 'k' ), c_c_( "Makasar" ) },
   (cIso639Info){ a2_( 'm', 'l' ), a3_( 'm', 'a', 'l' ), a3_( 'm', 'a', 'l' ), c_c_( "Malayalam" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 'n' ), a3_( 'm', 'a', 'n' ), c_c_( "Mandingo" ) },
   (cIso639Info){ a2_( 'm', 'i' ), a3_( 'm', 'a', 'o' ), a3_( 'm', 'r', 'i' ), c_c_( "Maori" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 'p' ), a3_( 'm', 'a', 'p' ), c_c_( "Austronesian languages" ) },
   (cIso639Info){ a2_( 'm', 'r' ), a3_( 'm', 'a', 'r' ), a3_( 'm', 'a', 'r' ), c_c_( "Marathi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'a', 's' ), a3_( 'm', 'a', 's' ), c_c_( "Masai" ) },
   (cIso639Info){ a2_( 'm', 's' ), a3_( 'm', 'a', 'y' ), a3_( 'm', 's', 'a' ), c_c_( "Malay" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'd', 'f' ), a3_( 'm', 'd', 'f' ), c_c_( "Moksha" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'd', 'r' ), a3_( 'm', 'd', 'r' ), c_c_( "Mandar" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'e', 'n' ), a3_( 'm', 'e', 'n' ), c_c_( "Mende" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'g', 'a' ), a3_( 'm', 'g', 'a' ), c_c_( "Irish, Middle (900-1200)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'i', 'c' ), a3_( 'm', 'i', 'c' ), c_c_( "Mi'kmaq; Micmac" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'i', 'n' ), a3_( 'm', 'i', 'n' ), c_c_( "Minangkabau" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'i', 's' ), a3_( 'm', 'i', 's' ), c_c_( "Uncoded languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'k', 'h' ), a3_( 'm', 'k', 'h' ), c_c_( "Mon-Khmer languages" ) },
   (cIso639Info){ a2_( 'm', 'g' ), a3_( 'm', 'l', 'g' ), a3_( 'm', 'l', 'g' ), c_c_( "Malagasy" ) },
   (cIso639Info){ a2_( 'm', 't' ), a3_( 'm', 'l', 't' ), a3_( 'm', 'l', 't' ), c_c_( "Maltese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'n', 'c' ), a3_( 'm', 'n', 'c' ), c_c_( "Manchu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'n', 'i' ), a3_( 'm', 'n', 'i' ), c_c_( "Manipuri" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'n', 'o' ), a3_( 'm', 'n', 'o' ), c_c_( "Manobo languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'o', 'h' ), a3_( 'm', 'o', 'h' ), c_c_( "Mohawk" ) },
   (cIso639Info){ a2_( 'm', 'n' ), a3_( 'm', 'o', 'n' ), a3_( 'm', 'o', 'n' ), c_c_( "Mongolian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'o', 's' ), a3_( 'm', 'o', 's' ), c_c_( "Mossi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'u', 'l' ), a3_( 'm', 'u', 'l' ), c_c_( "Multiple languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'u', 'n' ), a3_( 'm', 'u', 'n' ), c_c_( "Munda languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'u', 's' ), a3_( 'm', 'u', 's' ), c_c_( "Creek" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'w', 'l' ), a3_( 'm', 'w', 'l' ), c_c_( "Mirandese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'w', 'r' ), a3_( 'm', 'w', 'r' ), c_c_( "Marwari" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'y', 'n' ), a3_( 'm', 'y', 'n' ), c_c_( "Mayan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'm', 'y', 'v' ), a3_( 'm', 'y', 'v' ), c_c_( "Erzya" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'a', 'h' ), a3_( 'n', 'a', 'h' ), c_c_( "Nahuatl languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'a', 'i' ), a3_( 'n', 'a', 'i' ), c_c_( "North American Indian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'a', 'p' ), a3_( 'n', 'a', 'p' ), c_c_( "Neapolitan" ) },
   (cIso639Info){ a2_( 'n', 'a' ), a3_( 'n', 'a', 'u' ), a3_( 'n', 'a', 'u' ), c_c_( "Nauru" ) },
   (cIso639Info){ a2_( 'n', 'v' ), a3_( 'n', 'a', 'v' ), a3_( 'n', 'a', 'v' ), c_c_( "Navajo; Navaho" ) },
   (cIso639Info){ a2_( 'n', 'r' ), a3_( 'n', 'b', 'l' ), a3_( 'n', 'b', 'l' ), c_c_( "Ndebele, South; South Ndebele" ) },
   (cIso639Info){ a2_( 'n', 'd' ), a3_( 'n', 'd', 'e' ), a3_( 'n', 'd', 'e' ), c_c_( "Ndebele, North; North Ndebele" ) },
   (cIso639Info){ a2_( 'n', 'g' ), a3_( 'n', 'd', 'o' ), a3_( 'n', 'd', 'o' ), c_c_( "Ndonga" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'd', 's' ), a3_( 'n', 'd', 's' ), c_c_( "Low German; Low Saxon; German, Low; Saxon, Low" ) },
   (cIso639Info){ a2_( 'n', 'e' ), a3_( 'n', 'e', 'p' ), a3_( 'n', 'e', 'p' ), c_c_( "Nepali" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'e', 'w' ), a3_( 'n', 'e', 'w' ), c_c_( "Nepal Bhasa; Newari" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'i', 'a' ), a3_( 'n', 'i', 'a' ), c_c_( "Nias" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'i', 'c' ), a3_( 'n', 'i', 'c' ), c_c_( "Niger-Kordofanian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'i', 'u' ), a3_( 'n', 'i', 'u' ), c_c_( "Niuean" ) },
   (cIso639Info){ a2_( 'n', 'n' ), a3_( 'n', 'n', 'o' ), a3_( 'n', 'n', 'o' ), c_c_( "Norwegian Nynorsk; Nynorsk, Norwegian" ) },
   (cIso639Info){ a2_( 'n', 'b' ), a3_( 'n', 'o', 'b' ), a3_( 'n', 'o', 'b' ), c_c_( "Bokmål, Norwegian; Norwegian Bokmål" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'o', 'g' ), a3_( 'n', 'o', 'g' ), c_c_( "Nogai" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'o', 'n' ), a3_( 'n', 'o', 'n' ), c_c_( "Norse, Old" ) },
   (cIso639Info){ a2_( 'n', 'o' ), a3_( 'n', 'o', 'r' ), a3_( 'n', 'o', 'r' ), c_c_( "Norwegian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'q', 'o' ), a3_( 'n', 'q', 'o' ), c_c_( "N'Ko" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 's', 'o' ), a3_( 'n', 's', 'o' ), c_c_( "Pedi; Sepedi; Northern Sotho" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'u', 'b' ), a3_( 'n', 'u', 'b' ), c_c_( "Nubian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'w', 'c' ), a3_( 'n', 'w', 'c' ), c_c_( "Classical Newari; Old Newari; Classical Nepal Bhasa" ) },
   (cIso639Info){ a2_( 'n', 'y' ), a3_( 'n', 'y', 'a' ), a3_( 'n', 'y', 'a' ), c_c_( "Chichewa; Chewa; Nyanja" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'y', 'm' ), a3_( 'n', 'y', 'm' ), c_c_( "Nyamwezi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'y', 'n' ), a3_( 'n', 'y', 'n' ), c_c_( "Nyankole" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'y', 'o' ), a3_( 'n', 'y', 'o' ), c_c_( "Nyoro" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'n', 'z', 'i' ), a3_( 'n', 'z', 'i' ), c_c_( "Nzima" ) },
   (cIso639Info){ a2_( 'o', 'c' ), a3_( 'o', 'c', 'i' ), a3_( 'o', 'c', 'i' ), c_c_( "Occitan (post 1500)" ) },
   (cIso639Info){ a2_( 'o', 'j' ), a3_( 'o', 'j', 'i' ), a3_( 'o', 'j', 'i' ), c_c_( "Ojibwa" ) },
   (cIso639Info){ a2_( 'o', 'r' ), a3_( 'o', 'r', 'i' ), a3_( 'o', 'r', 'i' ), c_c_( "Oriya" ) },
   (cIso639Info){ a2_( 'o', 'm' ), a3_( 'o', 'r', 'm' ), a3_( 'o', 'r', 'm' ), c_c_( "Oromo" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'o', 's', 'a' ), a3_( 'o', 's', 'a' ), c_c_( "Osage" ) },
   (cIso639Info){ a2_( 'o', 's' ), a3_( 'o', 's', 's' ), a3_( 'o', 's', 's' ), c_c_( "Ossetian; Ossetic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'o', 't', 'a' ), a3_( 'o', 't', 'a' ), c_c_( "Turkish, Ottoman (1500-1928)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'o', 't', 'o' ), a3_( 'o', 't', 'o' ), c_c_( "Otomian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'a', 'a' ), a3_( 'p', 'a', 'a' ), c_c_( "Papuan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'a', 'g' ), a3_( 'p', 'a', 'g' ), c_c_( "Pangasinan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'a', 'l' ), a3_( 'p', 'a', 'l' ), c_c_( "Pahlavi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'a', 'm' ), a3_( 'p', 'a', 'm' ), c_c_( "Pampanga; Kapampangan" ) },
   (cIso639Info){ a2_( 'p', 'a' ), a3_( 'p', 'a', 'n' ), a3_( 'p', 'a', 'n' ), c_c_( "Panjabi; Punjabi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'a', 'p' ), a3_( 'p', 'a', 'p' ), c_c_( "Papiamento" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'a', 'u' ), a3_( 'p', 'a', 'u' ), c_c_( "Palauan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'e', 'o' ), a3_( 'p', 'e', 'o' ), c_c_( "Persian, Old (ca.600-400 B.C.)" ) },
   (cIso639Info){ a2_( 'f', 'a' ), a3_( 'p', 'e', 'r' ), a3_( 'f', 'a', 's' ), c_c_( "Persian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'h', 'i' ), a3_( 'p', 'h', 'i' ), c_c_( "Philippine languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'h', 'n' ), a3_( 'p', 'h', 'n' ), c_c_( "Phoenician" ) },
   (cIso639Info){ a2_( 'p', 'i' ), a3_( 'p', 'l', 'i' ), a3_( 'p', 'l', 'i' ), c_c_( "Pali" ) },
   (cIso639Info){ a2_( 'p', 'l' ), a3_( 'p', 'o', 'l' ), a3_( 'p', 'o', 'l' ), c_c_( "Polish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'o', 'n' ), a3_( 'p', 'o', 'n' ), c_c_( "Pohnpeian" ) },
   (cIso639Info){ a2_( 'p', 't' ), a3_( 'p', 'o', 'r' ), a3_( 'p', 'o', 'r' ), c_c_( "Portuguese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'r', 'a' ), a3_( 'p', 'r', 'a' ), c_c_( "Prakrit languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'p', 'r', 'o' ), a3_( 'p', 'r', 'o' ), c_c_( "Provençal, Old (to 1500); Occitan, Old (to 1500)" ) },
   (cIso639Info){ a2_( 'p', 's' ), a3_( 'p', 'u', 's' ), a3_( 'p', 'u', 's' ), c_c_( "Pushto; Pashto" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'q', 'a', 'a' ), a3_( 'q', 'a', 'a' ), c_c_( "Reserved for local use" ) },
   (cIso639Info){ a2_( 'q', 'u' ), a3_( 'q', 'u', 'e' ), a3_( 'q', 'u', 'e' ), c_c_( "Quechua" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'r', 'a', 'j' ), a3_( 'r', 'a', 'j' ), c_c_( "Rajasthani" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'r', 'a', 'p' ), a3_( 'r', 'a', 'p' ), c_c_( "Rapanui" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'r', 'a', 'r' ), a3_( 'r', 'a', 'r' ), c_c_( "Rarotongan; Cook Islands Maori" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'r', 'o', 'a' ), a3_( 'r', 'o', 'a' ), c_c_( "Romance languages" ) },
   (cIso639Info){ a2_( 'r', 'm' ), a3_( 'r', 'o', 'h' ), a3_( 'r', 'o', 'h' ), c_c_( "Romansh" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'r', 'o', 'm' ), a3_( 'r', 'o', 'm' ), c_c_( "Romany" ) },
   (cIso639Info){ a2_( 'r', 'o' ), a3_( 'r', 'u', 'm' ), a3_( 'r', 'o', 'n' ), c_c_( "Romanian; Moldavian; Moldovan" ) },
   (cIso639Info){ a2_( 'r', 'n' ), a3_( 'r', 'u', 'n' ), a3_( 'r', 'u', 'n' ), c_c_( "Rundi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'r', 'u', 'p' ), a3_( 'r', 'u', 'p' ), c_c_( "Aromanian; Arumanian; Macedo-Romanian" ) },
   (cIso639Info){ a2_( 'r', 'u' ), a3_( 'r', 'u', 's' ), a3_( 'r', 'u', 's' ), c_c_( "Russian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 'd' ), a3_( 's', 'a', 'd' ), c_c_( "Sandawe" ) },
   (cIso639Info){ a2_( 's', 'g' ), a3_( 's', 'a', 'g' ), a3_( 's', 'a', 'g' ), c_c_( "Sango" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 'h' ), a3_( 's', 'a', 'h' ), c_c_( "Yakut" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 'i' ), a3_( 's', 'a', 'i' ), c_c_( "South American Indian languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 'l' ), a3_( 's', 'a', 'l' ), c_c_( "Salishan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 'm' ), a3_( 's', 'a', 'm' ), c_c_( "Samaritan Aramaic" ) },
   (cIso639Info){ a2_( 's', 'a' ), a3_( 's', 'a', 'n' ), a3_( 's', 'a', 'n' ), c_c_( "Sanskrit" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 's' ), a3_( 's', 'a', 's' ), c_c_( "Sasak" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'a', 't' ), a3_( 's', 'a', 't' ), c_c_( "Santali" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'c', 'n' ), a3_( 's', 'c', 'n' ), c_c_( "Sicilian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'c', 'o' ), a3_( 's', 'c', 'o' ), c_c_( "Scots" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'e', 'l' ), a3_( 's', 'e', 'l' ), c_c_( "Selkup" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'e', 'm' ), a3_( 's', 'e', 'm' ), c_c_( "Semitic languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'g', 'a' ), a3_( 's', 'g', 'a' ), c_c_( "Irish, Old (to 900)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'g', 'n' ), a3_( 's', 'g', 'n' ), c_c_( "Sign Languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'h', 'n' ), a3_( 's', 'h', 'n' ), c_c_( "Shan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'i', 'd' ), a3_( 's', 'i', 'd' ), c_c_( "Sidamo" ) },
   (cIso639Info){ a2_( 's', 'i' ), a3_( 's', 'i', 'n' ), a3_( 's', 'i', 'n' ), c_c_( "Sinhala; Sinhalese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'i', 'o' ), a3_( 's', 'i', 'o' ), c_c_( "Siouan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'i', 't' ), a3_( 's', 'i', 't' ), c_c_( "Sino-Tibetan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'l', 'a' ), a3_( 's', 'l', 'a' ), c_c_( "Slavic languages" ) },
   (cIso639Info){ a2_( 's', 'k' ), a3_( 's', 'l', 'o' ), a3_( 's', 'l', 'k' ), c_c_( "Slovak" ) },
   (cIso639Info){ a2_( 's', 'l' ), a3_( 's', 'l', 'v' ), a3_( 's', 'l', 'v' ), c_c_( "Slovenian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'm', 'a' ), a3_( 's', 'm', 'a' ), c_c_( "Southern Sami" ) },
   (cIso639Info){ a2_( 's', 'e' ), a3_( 's', 'm', 'e' ), a3_( 's', 'm', 'e' ), c_c_( "Northern Sami" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'm', 'i' ), a3_( 's', 'm', 'i' ), c_c_( "Sami languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'm', 'j' ), a3_( 's', 'm', 'j' ), c_c_( "Lule Sami" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'm', 'n' ), a3_( 's', 'm', 'n' ), c_c_( "Inari Sami" ) },
   (cIso639Info){ a2_( 's', 'm' ), a3_( 's', 'm', 'o' ), a3_( 's', 'm', 'o' ), c_c_( "Samoan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'm', 's' ), a3_( 's', 'm', 's' ), c_c_( "Skolt Sami" ) },
   (cIso639Info){ a2_( 's', 'n' ), a3_( 's', 'n', 'a' ), a3_( 's', 'n', 'a' ), c_c_( "Shona" ) },
   (cIso639Info){ a2_( 's', 'd' ), a3_( 's', 'n', 'd' ), a3_( 's', 'n', 'd' ), c_c_( "Sindhi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'n', 'k' ), a3_( 's', 'n', 'k' ), c_c_( "Soninke" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'o', 'g' ), a3_( 's', 'o', 'g' ), c_c_( "Sogdian" ) },
   (cIso639Info){ a2_( 's', 'o' ), a3_( 's', 'o', 'm' ), a3_( 's', 'o', 'm' ), c_c_( "Somali" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'o', 'n' ), a3_( 's', 'o', 'n' ), c_c_( "Songhai languages" ) },
   (cIso639Info){ a2_( 's', 't' ), a3_( 's', 'o', 't' ), a3_( 's', 'o', 't' ), c_c_( "Sotho, Southern" ) },
   (cIso639Info){ a2_( 'e', 's' ), a3_( 's', 'p', 'a' ), a3_( 's', 'p', 'a' ), c_c_( "Spanish; Castilian" ) },
   (cIso639Info){ a2_( 's', 'c' ), a3_( 's', 'r', 'd' ), a3_( 's', 'r', 'd' ), c_c_( "Sardinian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'r', 'n' ), a3_( 's', 'r', 'n' ), c_c_( "Sranan Tongo" ) },
   (cIso639Info){ a2_( 's', 'r' ), a3_( 's', 'r', 'p' ), a3_( 's', 'r', 'p' ), c_c_( "Serbian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'r', 'r' ), a3_( 's', 'r', 'r' ), c_c_( "Serer" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 's', 'a' ), a3_( 's', 's', 'a' ), c_c_( "Nilo-Saharan languages" ) },
   (cIso639Info){ a2_( 's', 's' ), a3_( 's', 's', 'w' ), a3_( 's', 's', 'w' ), c_c_( "Swati" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'u', 'k' ), a3_( 's', 'u', 'k' ), c_c_( "Sukuma" ) },
   (cIso639Info){ a2_( 's', 'u' ), a3_( 's', 'u', 'n' ), a3_( 's', 'u', 'n' ), c_c_( "Sundanese" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'u', 's' ), a3_( 's', 'u', 's' ), c_c_( "Susu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'u', 'x' ), a3_( 's', 'u', 'x' ), c_c_( "Sumerian" ) },
   (cIso639Info){ a2_( 's', 'w' ), a3_( 's', 'w', 'a' ), a3_( 's', 'w', 'a' ), c_c_( "Swahili" ) },
   (cIso639Info){ a2_( 's', 'v' ), a3_( 's', 'w', 'e' ), a3_( 's', 'w', 'e' ), c_c_( "Swedish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'y', 'c' ), a3_( 's', 'y', 'c' ), c_c_( "Classical Syriac" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 's', 'y', 'r' ), a3_( 's', 'y', 'r' ), c_c_( "Syriac" ) },
   (cIso639Info){ a2_( 't', 'y' ), a3_( 't', 'a', 'h' ), a3_( 't', 'a', 'h' ), c_c_( "Tahitian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'a', 'i' ), a3_( 't', 'a', 'i' ), c_c_( "Tai languages" ) },
   (cIso639Info){ a2_( 't', 'a' ), a3_( 't', 'a', 'm' ), a3_( 't', 'a', 'm' ), c_c_( "Tamil" ) },
   (cIso639Info){ a2_( 't', 't' ), a3_( 't', 'a', 't' ), a3_( 't', 'a', 't' ), c_c_( "Tatar" ) },
   (cIso639Info){ a2_( 't', 'e' ), a3_( 't', 'e', 'l' ), a3_( 't', 'e', 'l' ), c_c_( "Telugu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'e', 'm' ), a3_( 't', 'e', 'm' ), c_c_( "Timne" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'e', 'r' ), a3_( 't', 'e', 'r' ), c_c_( "Tereno" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'e', 't' ), a3_( 't', 'e', 't' ), c_c_( "Tetum" ) },
   (cIso639Info){ a2_( 't', 'g' ), a3_( 't', 'g', 'k' ), a3_( 't', 'g', 'k' ), c_c_( "Tajik" ) },
   (cIso639Info){ a2_( 't', 'l' ), a3_( 't', 'g', 'l' ), a3_( 't', 'g', 'l' ), c_c_( "Tagalog" ) },
   (cIso639Info){ a2_( 't', 'h' ), a3_( 't', 'h', 'a' ), a3_( 't', 'h', 'a' ), c_c_( "Thai" ) },
   (cIso639Info){ a2_( 'b', 'o' ), a3_( 't', 'i', 'b' ), a3_( 'b', 'o', 'd' ), c_c_( "Tibetan" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'i', 'g' ), a3_( 't', 'i', 'g' ), c_c_( "Tigre" ) },
   (cIso639Info){ a2_( 't', 'i' ), a3_( 't', 'i', 'r' ), a3_( 't', 'i', 'r' ), c_c_( "Tigrinya" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'i', 'v' ), a3_( 't', 'i', 'v' ), c_c_( "Tiv" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'k', 'l' ), a3_( 't', 'k', 'l' ), c_c_( "Tokelau" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'l', 'h' ), a3_( 't', 'l', 'h' ), c_c_( "Klingon; tlhIngan-Hol" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'l', 'i' ), a3_( 't', 'l', 'i' ), c_c_( "Tlingit" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'm', 'h' ), a3_( 't', 'm', 'h' ), c_c_( "Tamashek" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'o', 'g' ), a3_( 't', 'o', 'g' ), c_c_( "Tonga (Nyasa)" ) },
   (cIso639Info){ a2_( 't', 'o' ), a3_( 't', 'o', 'n' ), a3_( 't', 'o', 'n' ), c_c_( "Tonga (Tonga Islands)" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'p', 'i' ), a3_( 't', 'p', 'i' ), c_c_( "Tok Pisin" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 's', 'i' ), a3_( 't', 's', 'i' ), c_c_( "Tsimshian" ) },
   (cIso639Info){ a2_( 't', 'n' ), a3_( 't', 's', 'n' ), a3_( 't', 's', 'n' ), c_c_( "Tswana" ) },
   (cIso639Info){ a2_( 't', 's' ), a3_( 't', 's', 'o' ), a3_( 't', 's', 'o' ), c_c_( "Tsonga" ) },
   (cIso639Info){ a2_( 't', 'k' ), a3_( 't', 'u', 'k' ), a3_( 't', 'u', 'k' ), c_c_( "Turkmen" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'u', 'm' ), a3_( 't', 'u', 'm' ), c_c_( "Tumbuka" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'u', 'p' ), a3_( 't', 'u', 'p' ), c_c_( "Tupi languages" ) },
   (cIso639Info){ a2_( 't', 'r' ), a3_( 't', 'u', 'r' ), a3_( 't', 'u', 'r' ), c_c_( "Turkish" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'u', 't' ), a3_( 't', 'u', 't' ), c_c_( "Altaic languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'v', 'l' ), a3_( 't', 'v', 'l' ), c_c_( "Tuvalu" ) },
   (cIso639Info){ a2_( 't', 'w' ), a3_( 't', 'w', 'i' ), a3_( 't', 'w', 'i' ), c_c_( "Twi" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 't', 'y', 'v' ), a3_( 't', 'y', 'v' ), c_c_( "Tuvinian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'u', 'd', 'm' ), a3_( 'u', 'd', 'm' ), c_c_( "Udmurt" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'u', 'g', 'a' ), a3_( 'u', 'g', 'a' ), c_c_( "Ugaritic" ) },
   (cIso639Info){ a2_( 'u', 'g' ), a3_( 'u', 'i', 'g' ), a3_( 'u', 'i', 'g' ), c_c_( "Uighur; Uyghur" ) },
   (cIso639Info){ a2_( 'u', 'k' ), a3_( 'u', 'k', 'r' ), a3_( 'u', 'k', 'r' ), c_c_( "Ukrainian" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'u', 'm', 'b' ), a3_( 'u', 'm', 'b' ), c_c_( "Umbundu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'u', 'n', 'd' ), a3_( 'u', 'n', 'd' ), c_c_( "Undetermined" ) },
   (cIso639Info){ a2_( 'u', 'r' ), a3_( 'u', 'r', 'd' ), a3_( 'u', 'r', 'd' ), c_c_( "Urdu" ) },
   (cIso639Info){ a2_( 'u', 'z' ), a3_( 'u', 'z', 'b' ), a3_( 'u', 'z', 'b' ), c_c_( "Uzbek" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'v', 'a', 'i' ), a3_( 'v', 'a', 'i' ), c_c_( "Vai" ) },
   (cIso639Info){ a2_( 'v', 'e' ), a3_( 'v', 'e', 'n' ), a3_( 'v', 'e', 'n' ), c_c_( "Venda" ) },
   (cIso639Info){ a2_( 'v', 'i' ), a3_( 'v', 'i', 'e' ), a3_( 'v', 'i', 'e' ), c_c_( "Vietnamese" ) },
   (cIso639Info){ a2_( 'v', 'o' ), a3_( 'v', 'o', 'l' ), a3_( 'v', 'o', 'l' ), c_c_( "Volapük" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'v', 'o', 't' ), a3_( 'v', 'o', 't' ), c_c_( "Votic" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'w', 'a', 'k' ), a3_( 'w', 'a', 'k' ), c_c_( "Wakashan languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'w', 'a', 'l' ), a3_( 'w', 'a', 'l' ), c_c_( "Wolaitta; Wolaytta" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'w', 'a', 'r' ), a3_( 'w', 'a', 'r' ), c_c_( "Waray" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'w', 'a', 's' ), a3_( 'w', 'a', 's' ), c_c_( "Washo" ) },
   (cIso639Info){ a2_( 'c', 'y' ), a3_( 'w', 'e', 'l' ), a3_( 'c', 'y', 'm' ), c_c_( "Welsh" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'w', 'e', 'n' ), a3_( 'w', 'e', 'n' ), c_c_( "Sorbian languages" ) },
   (cIso639Info){ a2_( 'w', 'a' ), a3_( 'w', 'l', 'n' ), a3_( 'w', 'l', 'n' ), c_c_( "Walloon" ) },
   (cIso639Info){ a2_( 'w', 'o' ), a3_( 'w', 'o', 'l' ), a3_( 'w', 'o', 'l' ), c_c_( "Wolof" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'x', 'a', 'l' ), a3_( 'x', 'a', 'l' ), c_c_( "Kalmyk; Oirat" ) },
   (cIso639Info){ a2_( 'x', 'h' ), a3_( 'x', 'h', 'o' ), a3_( 'x', 'h', 'o' ), c_c_( "Xhosa" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'y', 'a', 'o' ), a3_( 'y', 'a', 'o' ), c_c_( "Yao" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'y', 'a', 'p' ), a3_( 'y', 'a', 'p' ), c_c_( "Yapese" ) },
   (cIso639Info){ a2_( 'y', 'i' ), a3_( 'y', 'i', 'd' ), a3_( 'y', 'i', 'd' ), c_c_( "Yiddish" ) },
   (cIso639Info){ a2_( 'y', 'o' ), a3_( 'y', 'o', 'r' ), a3_( 'y', 'o', 'r' ), c_c_( "Yoruba" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'y', 'p', 'k' ), a3_( 'y', 'p', 'k' ), c_c_( "Yupik languages" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'a', 'p' ), a3_( 'z', 'a', 'p' ), c_c_( "Zapotec" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'b', 'l' ), a3_( 'z', 'b', 'l' ), c_c_( "Blissymbols; Blissymbolics; Bliss" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'e', 'n' ), a3_( 'z', 'e', 'n' ), c_c_( "Zenaga" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'g', 'h' ), a3_( 'z', 'g', 'h' ), c_c_( "Standard Moroccan Tamazight" ) },
   (cIso639Info){ a2_( 'z', 'a' ), a3_( 'z', 'h', 'a' ), a3_( 'z', 'h', 'a' ), c_c_( "Zhuang; Chuang" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'n', 'd' ), a3_( 'z', 'n', 'd' ), c_c_( "Zande languages" ) },
   (cIso639Info){ a2_( 'z', 'u' ), a3_( 'z', 'u', 'l' ), a3_( 'z', 'u', 'l' ), c_c_( "Zulu" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'u', 'n' ), a3_( 'z', 'u', 'n' ), c_c_( "Zuni" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'x', 'x' ), a3_( 'z', 'x', 'x' ), c_c_( "No linguistic content; Not applicable" ) },
   (cIso639Info){ a2_( '\0', '\0' ), a3_( 'z', 'z', 'a' ), a3_( 'z', 'z', 'a' ), c_c_( "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" ) }
};
cIso639InfoSlice const C_Iso639InfoValues = { .s=487, .v=raw };
